logging:
  level:
    root: warn
spring:
  application:
    name: ChatApp_Internal
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyentronghieu13052004@gmail.com
    password: sqbu nztc exlp qbdj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

# Application Configuration
app:
  mail:
    forgot_password_token-ms: ${APP_FORGOT_PASSWORD_TOKEN_MS:3600000}
    verify_email_token-ms: ${APP_VERIFY_EMAIL_TOKEN_MS:86400000}
  jwt:
    secret: ${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    access-token-expiration-ms: ${APP_JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
    refresh-token-expiration-ms: ${APP_JWT_REFRESH_TOKEN_EXPIRATION_MS:2592000000}

  cookie:
    refresh-token-name: ${APP_COOKIE_REFRESH_TOKEN_NAME:refresh_token}
    refresh-token-max-age: ${APP_COOKIE_REFRESH_TOKEN_MAX_AGE:2592000}

  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    allowed-methods: ${APP_CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,PATCH,OPTIONS}
    allowed-headers: ${APP_CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${APP_CORS_ALLOW_CREDENTIALS:true}

  verification:
    email-token-expiration-ms: ${APP_VERIFICATION_EMAIL_TOKEN_EXPIRATION_MS:86400000}
    reset-password-token-expiration-ms: ${APP_VERIFICATION_RESET_PASSWORD_TOKEN_EXPIRATION_MS:3600000}
    invitation-token-expiration-ms: ${APP_VERIFICATION_INVITATION_TOKEN_EXPIRATION_MS:604800000}

  base-url: ${APP_BASE_URL:http://localhost:8080}
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}
  frontend-oauth-redirect: http://localhost:3000/auth/google/callback

# Google config
google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
    client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket-name: ${AWS_S3_BUCKET}
    base-url: https://${AWS_S3_BUCKET}.s3.${AWS_S3_REGION}.amazonaws.com

upload:
  max-file-size: 10485760  # 10MB in bytes
  max-request-size: 52428800  # 50MB
  allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar
  allowed-image-extensions: jpg,jpeg,png,gif
